#!/bin/bash
 
version=0.2

chmod 755 scripts/*
scripts/init_kitchen
scripts/check_binaries

result=$?
if [ "$result" == "1" ]
then
  exit 0
fi

while :
do

 clear

 echo 
 echo "============================================================"
 echo " SGS Android Kitchen $version - by RMGeren (xda-developers.com)"
 echo
 echo "        Based on the HTC Android Kitchen - by dsixda" 
 echo "============================================================"
 echo
 echo "  1 - Get stock ROMs"
 echo "  2 - Set up working folder from ROM"
 echo "  3 - Add root permissions"
 echo "  4 - Deodex files in your ROM"
 echo "  5 - Zipalign all *.apk files to optimize RAM usage"
 echo "  6 - Disable boot screen sounds"
 echo "  7 - Change wipe status of ROM"
 echo "  8 - Change name of ROM"
 echo "  9 - Show working folder information"
 echo " 10 - Add task killer tweak for speed (stock ROM only)"
 echo " 11 - Add /data/app functionality"
 echo " 12 - Add BusyBox"
 echo " 13 - Add Nano text editor + sysro/sysrw"
 echo " 14 - Add Bash (command shell)"
 echo " 15 - Add /etc/init.d scripts"
 echo " 16 - Add custom boot animation functionality"
 echo " 17 - Sign APK file(s)"
 echo " 18 - Convert update-script or updater-script"
 echo " 19 - Check update-script for errors"
 echo " 20 - Run plugin scripts"
 echo " 21 - Add kernel to ROM"
 echo " 22 - Add modem to ROM" 
 echo 
 echo " 99 - Build ROM from working folder"
 echo
 echo "  u - Update/About kitchen"
 echo "  x - Exit"
 echo ""
 echo -n "Enter option: "
 read opt
 case $opt in
   1) scripts/get_stock_roms; continue;;
   2) clear; scripts/check_rom; continue;;
   3) scripts/do_root; continue;;
   4) scripts/do_deodex; continue;; 
   5) scripts/do_zipalign;;
   6) scripts/disable_sounds;;
   7) scripts/change_wipe;;
   8) scripts/change_rom_name;;
   9) scripts/show_rom_info;;
  10) scripts/task_killer;;
  11) scripts/add_data_app show_help;;
  12) scripts/add_busybox show_help;;
  13) scripts/add_nano show_help;;
  14) scripts/add_bash show_help;;
  15) scripts/add_busybox_run_parts show_help;;
  16) scripts/add_custom_boot_anim;;
  17) scripts/sign_apks; continue;;
  18) scripts/update_script_convert_menu; continue;;
  19) scripts/verify_update_script; continue;;
  20) scripts/run_plugins; continue;;
  21) scripts/add_kernel_to_update_script;;
  22) scripts/add_modem_to_update_script;;
  99) scripts/build_rom;;
  u) scripts/about $version; continue;;
  x) scripts/init_kitchen; clear; echo; echo "Goodbye."; echo; exit 1;;
  *) echo "Invalid option"; continue;;
 esac

  scripts/press_enter

done
